### ISSUE TITLE
1.20.1 missing JEI + integration 

### ISSUE THREAD

**Issue by choekstr** [Tfarcenim/crafting-station#93] opened 2023-10-18 13:13 UTC
MC ver: 1.20.1
Forge: 47.1.3
JEI ver: jei-1.20.1-forge-15.2.0.27
modpack: ATM9 0.2.6
craftingstation: 1.20.1-1

When using crafting station and looking up a recipe, either manually in JEI or by hitting "r" on an item in inventory, with appropriate crafting materials in inventory, there is no + from JEI for the recipes and thus no click to import recipe.

Using Crafting Station
![image](https://github.com/Tfarcenim/crafting-station/assets/161085/a7678613-1a8c-43ba-9f2f-02709ec0bd5e)

Using vanilla crafting table and what it should look like: 
![image](https://github.com/Tfarcenim/crafting-station/assets/161085/596770cf-5879-4b65-ad73-657b706f1bdb)

**Comment by Tfarcenim** [comment] 2023-10-30 19:03
Duplicate of #92

**Closed as completed by Tfarcenim** 2023-10-30 19:03 UTC
