### ISSUE TITLE
game crashes after 2.0.8 update

### ISSUE THREAD

**Issue by Mntldisorder** [Tfarcenim/crafting-station#28] opened 2019-10-29 17:38 UTC
My game crash if i try to use the crafting station. Got 2 different types of issues, 1 for trying to take out the item i wanted to craft but then also trying to take out the ingredients after 2 crashes.

Issue 1:
Time: 10/29/19 6:25 PM
Description: mouseClicked event handler
java.lang.RuntimeException: Slot 9 not in valid range - [0,9)

Issue 2:
Description: handleMouseClick() threw an exception when called from MouseTweaks.
java.lang.reflect.InvocationTargetException: null

Here is a link to the crash log from issue 2:

https://pastebin.com/rWnYBaR1

**Comment by Tfarcenim** [comment] 2019-10-29 19:24
Hmm, since the decompiler/reampper isn't working, I'm going to consider this a bug in corail until otherwise noted.

**Comment by Tfarcenim** [comment] 2019-10-29 20:02
Confirmed: This is a bug in Corail Tombstone 
![image](https://user-images.githubusercontent.com/44327798/67804329-199ef700-fa65-11e9-9c81-3402ca6b5b50.png)

They should only be checking slots 0 - 8, but due to the usage of <= instead of <, it's checking the 9 slot as well, but my crafting station doesn't have a 9 slot so it crashes instead.

**Comment by Tfarcenim** [comment] 2019-10-30 03:16
This was fixed on their side, closing now

**Closed by Tfarcenim** 2019-10-30 03:16 UTC
Labels: bug, bug in other software

**Comment by raziel23x** [comment] 2019-10-30 15:58
not fixed in 1.14.4 but fixed in 1.12.2 so bug still there for 1.14.4 unless they are waiting on it to be approved for 1.14.4
